### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

squeeze
vstack

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32


### Function 1 - *your function to illustrate*
torch.unsqueeze() / torch.squeeze()

In [9]:
# Example 1 - ### your explanation ###
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],[[5, 6, 7], [7, 8, 9]]])
print(a.shape)
print(a)
b = a.unsqueeze(2)
print(b.shape)
print(b)

torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])
torch.Size([2, 2, 1, 3])
tensor([[[[1, 2, 3]],

         [[3, 4, 5]]],


        [[[5, 6, 7]],

         [[7, 8, 9]]]])


In [29]:
c = b.squeeze(2)
print(c.shape)
print(c)
#squeeze 只能對只有one dim的施作
d = b.squeeze(1)
print(d.shape)
print(d)
e = b.view(2,1,1,-1)
print(e.shape)
print(e.squeeze(2).squeeze(1))

torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])
torch.Size([2, 2, 1, 3])
tensor([[[[1, 2, 3]],

         [[3, 4, 5]]],


        [[[5, 6, 7]],

         [[7, 8, 9]]]])
torch.Size([2, 1, 1, 6])
tensor([[1, 2, 3, 3, 4, 5],
        [5, 6, 7, 7, 8, 9]])


### Function 2 - your function to illustrate
squeeze


In [33]:
# Example 1 - ### your explanation ###
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.vstack((a,b))


tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
# Example 2 - ### your explanation ###
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.vstack((a,b))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

### Function 3 - your function to illustrate

In [35]:
# Example 1 - ### your explanation ###
src = torch.tensor([[4, 3, 5],
                        [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

In [47]:
# Example 2 - ### your explanation ###
tak = torch.tensor([src.reshape(-1)[0], src.reshape(-1)[2] , src.reshape(-1)[5]])

tak

tensor([4, 5, 8])

### Function 4 - your function to illustrate

In [50]:
# Example 1 - ### your explanation ###
x = torch.randn(2, 3)
x.shape,x

(torch.Size([2, 3]),
 tensor([[ 0.1620,  0.8380,  0.4707],
         [ 1.6173, -1.4922, -1.3101]]))

In [51]:
# Example 2 - ### your explanation ###
y = torch.transpose(x, 0, 1)
y.shape, y

(torch.Size([3, 2]),
 tensor([[ 0.1620,  1.6173],
         [ 0.8380, -1.4922],
         [ 0.4707, -1.3101]]))